/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package BAI4;

import BAI2.DES;
import static BAI2.DES.decrypt;
import static BAI2.DES.encrypt;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.Buffer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class DESCS extends javax.swing.JFrame {

    /**
     * Creates new form DESCS
     */
    public DESCS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtkhoa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtmahoa = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtvanban = new javax.swing.JTextArea();
        btnMoKhoaA = new javax.swing.JButton();
        btnMaHoa = new javax.swing.JButton();
        btnMoKhoaB = new javax.swing.JButton();
        btnGhiFile = new javax.swing.JButton();
        btnGiaima = new javax.swing.JButton();
        btnhienthi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Input Key: ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Plaintext: ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("CipherText: ");

        txtmahoa.setColumns(20);
        txtmahoa.setRows(5);
        jScrollPane1.setViewportView(txtmahoa);

        txtvanban.setColumns(20);
        txtvanban.setRows(5);
        jScrollPane2.setViewportView(txtvanban);

        btnMoKhoaA.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMoKhoaA.setText("Mở Khóa A");
        btnMoKhoaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoKhoaAActionPerformed(evt);
            }
        });

        btnMaHoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMaHoa.setText("Mã Hóa");
        btnMaHoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaHoaActionPerformed(evt);
            }
        });

        btnMoKhoaB.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnMoKhoaB.setText("Mở Khóa B");
        btnMoKhoaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoKhoaBActionPerformed(evt);
            }
        });

        btnGhiFile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGhiFile.setText("Ghi File");
        btnGhiFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGhiFileActionPerformed(evt);
            }
        });

        btnGiaima.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGiaima.setText("Giải Mã");
        btnGiaima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGiaimaActionPerformed(evt);
            }
        });

        btnhienthi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnhienthi.setText("All Show");
        btnhienthi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhienthiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(btnMaHoa)
                        .addGap(79, 79, 79)
                        .addComponent(btnMoKhoaA)
                        .addGap(72, 72, 72)
                        .addComponent(btnMoKhoaB)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGhiFile))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtkhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2))))
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGiaima)
                .addGap(120, 120, 120)
                .addComponent(btnhienthi)
                .addGap(152, 152, 152))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtkhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel2)
                        .addGap(134, 134, 134))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMoKhoaA)
                            .addComponent(btnMaHoa)
                            .addComponent(btnMoKhoaB)
                            .addComponent(btnGhiFile))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGiaima)
                    .addComponent(btnhienthi))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMoKhoaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoKhoaAActionPerformed
        try{
            BufferedReader br = null;
            String fileName = "D:\\KhoaA.txt";
            br = new BufferedReader(new FileReader(fileName));
            StringBuffer sb = new StringBuffer();
            JOptionPane.showMessageDialog(null, "Đã mở File");
            char[] ca = new char[5];
            while (br.ready()){
            int len = br.read(ca);
            sb.append(ca,0,len);
        }
        br.close();
            System.out.println("Du Lieu la: " + " " + sb);
            String chuoi = sb.toString();
            txtkhoa.setText(chuoi);
        }catch(IOException ex)
        {
            Logger.getLogger(DESCS.class.getName()).log(Level.SEVERE, null,ex);
        }
    }//GEN-LAST:event_btnMoKhoaAActionPerformed

    private void btnGiaimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGiaimaActionPerformed
        FileInputStream fis2 = null;
        try{
            String key = txtkhoa.getText();
            fis2 = new FileInputStream("D:\\EnDes.txt");
            FileOutputStream fos2 = new FileOutputStream("D:\\DeDes.txt");
            decrypt(key, fis2, fos2);
            BufferedReader br = null;
            String fileName = "D:\\DeDes.txt";
            br = new BufferedReader(new FileReader(fileName));
            StringBuffer sb = new StringBuffer();
            JOptionPane.showMessageDialog(null, "Đã Giải Mã");
            char[] ca = new char[5];
            while(br.ready())
            {
                int len = br.read(ca);
                sb.append(ca,0,len);
            }
            br.close();
            System.out.println("Du Lieu La: " + " " + sb);
            String chuoi = sb.toString();
            txtvanban.setText(chuoi);
        }catch(Throwable ex){}          
    }//GEN-LAST:event_btnGiaimaActionPerformed

    private void btnhienthiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhienthiActionPerformed
        try{
           BufferedReader br = null;
           String fileName = "D:\\DeDes.txt";
           br = new BufferedReader(new FileReader(fileName));
           StringBuffer sb =  new StringBuffer();
           JOptionPane.showMessageDialog(null, "Đã mở file");
           char[] ca = new char[5];
           while(br.ready())
           {
               int len = br.read(ca);
               sb.append(ca,0,len);
           }
           br.close();
           String ff="D:\\EnDes.txt";
           br = new BufferedReader(new FileReader(ff));
           StringBuffer sb1 = new StringBuffer();
           char[] ca1 =  new char[5];
            while (br.ready()){
                int len = br.read(ca1);
                sb1.append(ca1,0,len);
            }
            System.out.println("Du Lieu La: "+" "+ sb);
            String chuoi = sb.toString();
            String chuoi1 = sb1.toString();
//            txtvanban.setText(chuoi);                      ====================================
            txtmahoa.setText(chuoi1);
        }catch(IOException ex){}
    }//GEN-LAST:event_btnhienthiActionPerformed

    private void btnMaHoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaHoaActionPerformed
        try{
            String key = txtkhoa.getText();
            FileInputStream fis = new FileInputStream("D:\\Des.txt");
            FileOutputStream fos = new FileOutputStream("D:\\EnDes.txt");
            encrypt(key, fis, fos);
            JOptionPane.showMessageDialog(null, "Đã mã hóa văn bản");
        }catch(Throwable e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnMaHoaActionPerformed

    private void btnMoKhoaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoKhoaBActionPerformed
        try{
            BufferedReader br = null;
            String fileName = "D:\\KhoaB.txt";
            br = new BufferedReader(new FileReader(fileName));
            StringBuffer sb = new StringBuffer();
            JOptionPane.showMessageDialog(null, "Đã mở file");
            char[] ca = new char[5];
            while(br.ready()){
                int len = br.read(ca);
                sb.append(ca,0,len);
            }
            br.close();
            System.out.println("Du Lieu la: "+ " "+sb);
            String chuoi = sb.toString();
            txtkhoa.setText(chuoi);
        }catch(IOException ex)
        {
            Logger.getLogger(DESCS.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMoKhoaBActionPerformed

    private void btnGhiFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGhiFileActionPerformed
        try{
            BufferedWriter bw = null;
            String fileName = "D:\\Des.txt";
            String s = txtvanban.getText();
            bw = new BufferedWriter(new FileWriter(fileName));
            bw.write(s);
            bw.close();
            JOptionPane.showMessageDialog(null, "Đã ghi File");
       
        }catch(IOException ex)
        {
            Logger.getLogger(DESCS.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGhiFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DESCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DESCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DESCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DESCS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DESCS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGhiFile;
    private javax.swing.JButton btnGiaima;
    private javax.swing.JButton btnMaHoa;
    private javax.swing.JButton btnMoKhoaA;
    private javax.swing.JButton btnMoKhoaB;
    private javax.swing.JButton btnhienthi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtkhoa;
    private javax.swing.JTextArea txtmahoa;
    private javax.swing.JTextArea txtvanban;
    // End of variables declaration//GEN-END:variables
}
