/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package THIKT;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.security.MessageDigest;
import java.security.spec.KeySpec;
import java.util.Base64;
import javax.crypto.Cipher;
import javax.crypto.SecretKey;
import javax.crypto.SecretKeyFactory;
import javax.crypto.spec.DESedeKeySpec;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */
public class FormGui extends javax.swing.JFrame {

    /**
     * Creates new form FormGui
     */
    char pf[][]={{'T','U','E','N','E'},
                 {'N','P','H','B','D'},
                 {'E','F','G','I','K'},
                 {'L','P','Q','S','T'},
                 {'U','V','W','X','Z'}        
        };
    public FormGui() {
        initComponents();
    }
 private static final String UNICODE_FORMAT="UTF8";
    private static final String DESEDE_ENCRYTION_SCHENE="DESede";
    private KeySpec myKeySpec;
    private SecretKeyFactory mySecretKeyFactory;
    private Cipher cipher;
    byte[] keyAsBytes;
    private String myEncryptionKey;
    private String myEncryptionScheme;
    SecretKey key;
    
    
    public String encrypt (String unencryptedString) {
        String encryptedString = null;
        try { 
            cipher.init(Cipher.ENCRYPT_MODE, key);
            byte[] plainText = unencryptedString.getBytes(UNICODE_FORMAT);
            byte[] encryptedText = cipher.doFinal(plainText);
            byte[] encrypted = Base64.getEncoder().encode(encryptedText);
            encryptedString = new String(encrypted);
        } catch (Exception e){
        }
        return encryptedString;
    }
    public String decrypt(String encryptedString) {
        String decryptedText = null;
        try { 
            cipher.init(Cipher.DECRYPT_MODE, key);
//            BASE64Decoder base64decoder = new BASE64Decoder; 
//            byte[] encryptedText = base64decode.decodeBuffer(encryptedString);
           byte[] decrypt = Base64.getDecoder().decode(decryptedText);
           byte[] plainText = cipher.doFinal(decrypt);
            String a = new String(plainText);
            System.out.println("Chuoi plaintext:" +a);
            decryptedText = a; 
        } catch (Exception e){
            e.printStackTrace();
        }
        return decryptedText;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtND1 = new javax.swing.JTextField();
        txtK1 = new javax.swing.JTextField();
        txtMAHOA1 = new javax.swing.JTextField();
        txtND2 = new javax.swing.JTextField();
        txtBam1 = new javax.swing.JTextField();
        txtNoivaBam2 = new javax.swing.JTextField();
        txtK2 = new javax.swing.JTextField();
        txtMH2 = new javax.swing.JTextField();
        btnmh1 = new javax.swing.JButton();
        btnBam1 = new javax.swing.JButton();
        btnLuuFileBam = new javax.swing.JButton();
        btnnoichuoi2 = new javax.swing.JButton();
        btnmahoa2 = new javax.swing.JButton();
        btnghifilemahoa2 = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("FORM GỬI");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Khóa 1:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Nội Dung 1:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("ND Mã Hóa 1:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Bản mã băm:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Nội Dung 2:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Nối chuỗi Nội Dung 2 và Bản Băm:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Khóa 2:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("ND Mã Hóa 2:");

        txtND1.setText("Hello");

        txtK1.setText("NguyenPhamTuyen");

        txtND2.setText("Tuyen");

        txtK2.setText("nguyenphamtuyenthuchanhbmtt");
        txtK2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtK2ActionPerformed(evt);
            }
        });

        btnmh1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnmh1.setText("Mã Hóa ND1");
        btnmh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmh1ActionPerformed(evt);
            }
        });

        btnBam1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBam1.setText("Băm ND Mã Hóa 1");
        btnBam1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBam1ActionPerformed(evt);
            }
        });

        btnLuuFileBam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLuuFileBam.setText("Lưu File Băm");
        btnLuuFileBam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuFileBamActionPerformed(evt);
            }
        });

        btnnoichuoi2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnnoichuoi2.setText("Nối chuỗi");
        btnnoichuoi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnoichuoi2ActionPerformed(evt);
            }
        });

        btnmahoa2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnmahoa2.setText("Mã Hóa ND2");
        btnmahoa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmahoa2ActionPerformed(evt);
            }
        });

        btnghifilemahoa2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnghifilemahoa2.setText("Ghi File");
        btnghifilemahoa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnghifilemahoa2ActionPerformed(evt);
            }
        });

        btnexit.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        btnexit.setText("Thoát");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(301, 301, 301)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(186, 186, 186)
                                .addComponent(txtK2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(142, 142, 142)
                                .addComponent(txtMH2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNoivaBam2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(142, 142, 142)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtBam1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtND2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtMAHOA1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtK1, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                                            .addComponent(txtND1))))))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBam1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnmh1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLuuFileBam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnnoichuoi2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnmahoa2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnghifilemahoa2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnexit, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtND1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtK1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmh1))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMAHOA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBam1))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtBam1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLuuFileBam))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtND2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnnoichuoi2))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtNoivaBam2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtK2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnmahoa2))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtMH2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnghifilemahoa2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(btnexit)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
    System.exit(0);
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnmh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmh1ActionPerformed
    try{
        String banro = this.txtND1.getText();        
        banro=banro.toUpperCase();
        banro=banro.replace('J','I');
        String banma = mahoa(banro);
        this.txtMAHOA1.setText(banma);
        System.out.println("ND 1 sau khi ma hoa :"+banma);
        String fileName = "D:\\MaHoaND1.txt";
        BufferedWriter ll = new BufferedWriter(new FileWriter(fileName));
        ll.write(banma.toString());
        ll.close();
        JOptionPane.showMessageDialog(null, "Bạn Đã Mã Hóa ND1 Thành Công");
        }catch(Exception ex)
        {
                System.out.println("Lỗi Mã Hóa ND 1 :" + ex); 
        }
    }//GEN-LAST:event_btnmh1ActionPerformed

    private void btnBam1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBam1ActionPerformed
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            md.update(txtMAHOA1.getText().getBytes());
            byte byteData[] = md.digest();
            StringBuffer sb = new StringBuffer();
            for(int i = 0; i < byteData.length; i++)
            {
                sb.append(Integer.toString((byteData[i] & 0xff) + 0x100,16).substring(1));
            }
            String bamm1 = sb.toString();
            StringBuffer hexString = new StringBuffer();
            for (int i = 0; i < byteData.length; i++) {
                String hex = Integer.toHexString(0xff & byteData[i]);
                if(hex.length() == 1)
                    hexString.append('0');
                hexString.append(hex);
            }
            String bamm2 = hexString.toString();
            if(bamm1.equals(bamm2) == true)
            {
                txtBam1.setText(bamm1);   
                System.out.println("NoiDung MH1 sau khi Bam:" + bamm1);
            }           
            
            JOptionPane.showMessageDialog(null, "Bạn Đã Băm ND 1 Thành Công");
            }catch(Exception ex)
            {
                System.out.println("Lỗi băm ND1 :" + ex); 
        }                      
    }//GEN-LAST:event_btnBam1ActionPerformed

    private void btnnoichuoi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnoichuoi2ActionPerformed
    try{
        String MH1 = txtBam1.getText();
        String ND2 = txtND2.getText();
        String bam = "";
        bam = MH1 + ND2;
        txtNoivaBam2.setText(bam);
        System.out.println("Noi Noi Dung 2 Va Ban Bam :"+bam);
        String fileName = "D:\\NoiND2VaBanBam.txt";
        BufferedWriter bw = new BufferedWriter(new FileWriter(fileName));
        bw.write(bam.toString());
        bw.close();
        JOptionPane.showMessageDialog(null, "Ban Da Noi ND2 Va Ban Bam Thanh Cong!");
        }catch(Exception ex)
            {
                System.out.println("Lỗi Nối Chuỗi ND2 va Ban Bam :" + ex); 
        }
    }//GEN-LAST:event_btnnoichuoi2ActionPerformed

    private void btnLuuFileBamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuFileBamActionPerformed
    try{
        String hexString = txtBam1.getText();
        String fileName = "D:\\BamND1.txt";
        BufferedWriter bw = new BufferedWriter(new FileWriter(fileName));
        bw.write(hexString);
        JOptionPane.showMessageDialog(null, "Ban Da Luu File Bam ND Ma Hoa 1 Thanh Cong!");
        bw.close();
    }catch(Exception ex)
        {
                System.out.println("Khong the Luu File!"); 
        } 
    }//GEN-LAST:event_btnLuuFileBamActionPerformed

    private void btnmahoa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmahoa2ActionPerformed
    try{ 
            myEncryptionKey=txtK2.getText();
            myEncryptionScheme=DESEDE_ENCRYTION_SCHENE;
            keyAsBytes=myEncryptionKey.getBytes(UNICODE_FORMAT);
            myKeySpec=new DESedeKeySpec(keyAsBytes);
            mySecretKeyFactory=SecretKeyFactory.getInstance(myEncryptionScheme);
            cipher=Cipher.getInstance(myEncryptionScheme);
            key=mySecretKeyFactory.generateSecret(myKeySpec);
            System.out.println("Key :"+key);
            String plainText=txtNoivaBam2.getText();
            JOptionPane.showMessageDialog(null, "Ban Da Ma Hoa Noi Dung 2 va Ban Bam Thanh Cong!");
            String encrypted=encrypt(plainText);
            System.out.println("Gia Tri Ma Hoa :"+encrypted);
            txtMH2.setText(encrypted);
        } catch (Exception ex) {
                System.out.println("Khong the Ma Hoa ND 2 Va Ban Bam!"); 
        }
    }//GEN-LAST:event_btnmahoa2ActionPerformed

    private void btnghifilemahoa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnghifilemahoa2ActionPerformed
    try{
        String hexString = txtMH2.getText();
        String fileName = "D:\\NoiDungMH2.txt";
        BufferedWriter bw = new BufferedWriter(new FileWriter(fileName));
        bw.write(hexString);
        JOptionPane.showMessageDialog(null, "Ban Da Ghi File Noi Dung 2 va Ban Bam Sau Ma Hoa Thanh Cong!");
        bw.close();
    }catch(Exception ex)
        {
                System.out.println("Khong the Ghi File !"); 
        } 
    }//GEN-LAST:event_btnghifilemahoa2ActionPerformed

    private void txtK2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtK2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtK2ActionPerformed
    private String mahoa(String banro)
    {
        int n=banro.length();
        int i=0;
        String banma="";
        char a,b;
        while(i<n)
        {
            if(i==n-1)
            {
                a=banro.charAt(i);
                b='X';
                i++;
            }else
            {
                a=banro.charAt(i);
                b=banro.charAt(i+1);
                if(a==b)
                {
                    b='X';
                    i++;
                }else{
                    i+=2;
                }
            }
            banma+=thayThe(a,b);
        }
        return banma;
    }
    String thayThe(char a,char b)
    {
        String vta=timViTri(a);
        String vtb=timViTri(b);
        char x,y;
        if(vta.charAt(0) == vtb.charAt(0))
        {
            x=pf[(vta.charAt(0)-'0')][((vta.charAt(1)-'0')+1)%5];
            y=pf[(vtb.charAt(0)-'0')][((vtb.charAt(1)-'0')+1)%5];
            return x+""+y;
        }
        if(vta.charAt(1) == vtb.charAt(1))
        {
            x=pf[((vta.charAt(0)-'0')+1)%5][(vta.charAt(1)-'0')];
            y=pf[((vtb.charAt(0)-'0')+1)%5][(vtb.charAt(1)-'0')];
            return x+""+y;
        }
        x=pf[(vta.charAt(0)-'0')][(vtb.charAt(1)-'0')];
        y=pf[(vtb.charAt(0)-'0')][(vta.charAt(1)-'0')];
        return x+""+y;
    }
    
    private String timViTri(char a)
    {
        for (int i = 0; i < 5; i++) {
            for (int j = 0; j < 5; j++) {
                if(pf[i][j]==a)
                    return i+""+j;
            }
        }
        return "";
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBam1;
    private javax.swing.JButton btnLuuFileBam;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnghifilemahoa2;
    private javax.swing.JButton btnmahoa2;
    private javax.swing.JButton btnmh1;
    private javax.swing.JButton btnnoichuoi2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtBam1;
    private javax.swing.JTextField txtK1;
    private javax.swing.JTextField txtK2;
    private javax.swing.JTextField txtMAHOA1;
    private javax.swing.JTextField txtMH2;
    private javax.swing.JTextField txtND1;
    private javax.swing.JTextField txtND2;
    private javax.swing.JTextField txtNoivaBam2;
    // End of variables declaration//GEN-END:variables
}
