/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BAI1;

/**
 *
 * @author ESC
 */
public class RailFence extends javax.swing.JFrame {

    /**
     * Creates new form RailFence
     */
    public RailFence() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txttieude = new javax.swing.JLabel();
        txtbanro = new javax.swing.JLabel();
        txtmakhoa = new javax.swing.JLabel();
        txtbanma = new javax.swing.JLabel();
        btnmahoa = new javax.swing.JButton();
        btngiaima = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtbr = new javax.swing.JTextArea();
        txtkhoa = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtbm = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txttieude.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txttieude.setText("MÃ HÓA RAIL FENCE");

        txtbanro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtbanro.setText("Plaintext:");

        txtmakhoa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtmakhoa.setText("Key:");

        txtbanma.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtbanma.setText("Ciphertext:");

        btnmahoa.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        btnmahoa.setText("v Encypt v");
        btnmahoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmahoaActionPerformed(evt);
            }
        });

        btngiaima.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        btngiaima.setText("^ Dencypt ^");
        btngiaima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngiaimaActionPerformed(evt);
            }
        });

        txtbr.setColumns(20);
        txtbr.setRows(5);
        jScrollPane1.setViewportView(txtbr);

        txtbm.setColumns(20);
        txtbm.setRows(5);
        jScrollPane2.setViewportView(txtbm);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txttieude)
                .addGap(191, 191, 191))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtbanma)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtbanro)
                                    .addComponent(txtmakhoa))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtkhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(btnmahoa)
                        .addGap(113, 113, 113)
                        .addComponent(btngiaima)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txttieude)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtbanro)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtkhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmakhoa))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnmahoa)
                    .addComponent(btngiaima))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(txtbanma, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmahoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmahoaActionPerformed
        int k=Integer.valueOf(this.txtkhoa.getText());
        String s=this.txtbr.getText();
        int n=s.length();
        int sd,sc;
        sd=k;
        sc=n/sd+1;
        char hr[][]=new char[sd][sc];
        int c=0,d=0;
        int sodu=n%sd;
        for (int i = 0; i < n; i++) {
            hr[d][c]=s.charAt(i);
            d++;
            if(d==k)
            {
                c++; 
                d=0;
            }
        }
        String kq="";
        int sokytu=sc;
        for(int i = 0;i<sd;i++)
        {
            if(i>=sodu) sokytu=sc-1;
            for(int j=0;j<sokytu;j++)
                kq=kq+hr[i][j];
        }
        this.txtbm.setText(kq);
    }//GEN-LAST:event_btnmahoaActionPerformed

    private void btngiaimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngiaimaActionPerformed
        int k=Integer.valueOf(this.txtkhoa.getText());
        String s=this.txtbm.getText();
        int n=s.length();
        int sd,sc;
        sd=k;
        sc=n/sd+1;
        
        int sodu=n%sd; //coi lai
        String kq="";
        int sokytu=sc;
        
        char hr[][]=new char [sd][sc];
        int t=0;
        for (int i = 0; i < sd; i++) {
            if(i>=sodu)
                sokytu=sc-1;
            for (int j = 0; j < sokytu; j++) 
            {
                hr[i][j]=s.charAt(t);
                t++;
            }
        }
        int c=0,d=0;
        for (int i = 0; i < n; i++) {
            kq+=hr[d][c];
            d++;
            if(d==k)
            {
                c++;
                d=0;
            }
            this.txtbr.setText(kq);
        }
    }//GEN-LAST:event_btngiaimaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RailFence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RailFence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RailFence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RailFence.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RailFence().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btngiaima;
    private javax.swing.JButton btnmahoa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel txtbanma;
    private javax.swing.JLabel txtbanro;
    private javax.swing.JTextArea txtbm;
    private javax.swing.JTextArea txtbr;
    private javax.swing.JTextField txtkhoa;
    private javax.swing.JLabel txtmakhoa;
    private javax.swing.JLabel txttieude;
    // End of variables declaration//GEN-END:variables
}
